{
//if necessary also normal projections and looip over massbins
	using namespace RooFit;
//	TFile *_file0 = TFile::Open("compared_templates_7415v2_v5_data_ecorr_pas.root");
// 	TFile *_file1 = TFile::Open("compared_moriond16v1_sync_v5.root");
 //	TFile *_file1 = TFile::Open("compared_moriond16v1_sync_v4_data.root");

	TFile *_file0 = TFile::Open("compared_templates_7415v2_v5_data_ecorr_pas_fullmass.root");
// 	TFile *_file1 = TFile::Open("compared_moriond16v1_sync_v5_fullmass.root");
 	TFile *_file1 = TFile::Open("compared_moriond16v1_sync_v4_data_fullmass.root");
 	_file0->cd();	
//	RooDataHist* dppEBEB_old= (RooDataHist*)(wtemplates->data("unrolled_template_pp_2D_EBEB_mb_230_12999"));
//    RooDataHist* dppEBEE_old= (RooDataHist*)(wtemplates->data("unrolled_template_pp_2D_EBEE_mb_320_12999"));
//	RooDataHist* dppEBEB_old= (RooDataHist*)(wtemplates->data("unrolled_template_pp_2D_EBEB_mb_800_12999"));
//    RooDataHist* dppEBEE_old= (RooDataHist*)(wtemplates->data("unrolled_template_pp_2D_EBEE_mb_800_12999"));
	RooDataHist* dppEBEB_old= (RooDataHist*)(wtemplates->data("unrolled_template_mix_ff_2D_EBEB_mb_230_12999"));
   RooDataHist* dppEBEE_old= (RooDataHist*)(wtemplates->data("unrolled_template_mix_ff_2D_EBEE_mb_320_12999"));
///	RooDataHist* dppEBEB_old= (RooDataHist*)(wtemplates->data("unrolled_template_mix_ff_2D_EBEB_mb_800_12999"));
//   RooDataHist* dppEBEE_old= (RooDataHist*)(wtemplates->data("unrolled_template_mix_ff_2D_EBEE_mb_800_12999"));
	cout << __LINE__ << endl;
	RooRealVar* templateNdim2d_unroll= wtemplates->var("templateNdim2d_unroll");
    TH1D*  ppEBEB_old=new TH1D("ppEBEB_old","ppEBEB_old",9,0,9);
    dppEBEB_old->fillHistogram(ppEBEB_old,RooArgList(*templateNdim2d_unroll));
	
	cout << __LINE__ << endl;
    TH1D*  ppEBEE_old=new TH1D("ppEBEE_old","ppEBEE_old",9,0,9);
    dppEBEE_old->fillHistogram(ppEBEE_old,RooArgList(*templateNdim2d_unroll));
 	_file1->cd();	
//	RooDataHist* dppEBEB_new= (RooDataHist*)(wtemplates->data("unrolled_template_pp_2D_EBEB_mb_230_12999"));
//	RooDataHist* dppEBEE_new= (RooDataHist*)(wtemplates->data("unrolled_template_pp_2D_EBEE_mb_320_12999"));
//	RooDataHist* dppEBEB_new= (RooDataHist*)(wtemplates->data("unrolled_template_pp_2D_EBEB_mb_800_12999"));
//    RooDataHist* dppEBEE_new= (RooDataHist*)(wtemplates->data("unrolled_template_pp_2D_EBEE_mb_800_12999"));
//	RooDataHist* dppEBEB_new= (RooDataHist*)(wtemplates->data("unrolled_template_mix_ff_2D_EBEB_mb_800_12999"));
//	RooDataHist* dppEBEE_new= (RooDataHist*)(wtemplates->data("unrolled_template_mix_ff_2D_EBEE_mb_800_12999"));
	RooDataHist* dppEBEB_new= (RooDataHist*)(wtemplates->data("unrolled_template_mix_ff_2D_EBEB_mb_230_12999"));
	RooDataHist* dppEBEE_new= (RooDataHist*)(wtemplates->data("unrolled_template_mix_ff_2D_EBEE_mb_320_12999"));
    TH1D*  ppEBEB_new=new TH1D("ppEBEB_new","ppEBEB_new",9,0,9);
    dppEBEB_new->fillHistogram(ppEBEB_new,RooArgList(*templateNdim2d_unroll));	
    TH1D*  ppEBEE_new=new TH1D("ppEBEE_new","ppEBEE_new",9,0,9);
    dppEBEE_new->fillHistogram(ppEBEE_new,RooArgList(*templateNdim2d_unroll));
    gStyle->SetOptStat(0);


    TCanvas * canvEBEB = new TCanvas("ffEBEB","ffEBEB");
	TCanvas * canvEBEE = new TCanvas("ffEBEE","ffEBEE");
    canvEBEB->Divide(1,2);
    canvEBEB->cd(1);
    gPad->SetPad(0., 0.3, 1., 1.0);
    gPad->SetLogy();
    canvEBEB->cd(2);
    gPad->SetPad(0., 0.0, 1.,0.3);
    canvEBEB->cd(1);
    TLegend* leg= new TLegend(0.5,0.8,0.9,0.9);
    ppEBEB_new->GetYaxis()->SetRangeUser(1e-5,3);
    ppEBEB_new->SetLineColor(kBlack);
    ppEBEB_new->SetMarkerColor(kBlack);
    ppEBEB_new->SetMarkerSize(1.3);
    ppEBEB_new->SetLineWidth(2);
    ppEBEB_old->SetFillColor(kRed);
    ppEBEB_old->SetFillStyle(3002);
    ppEBEB_new->GetYaxis()->SetTitle("Arbitrary Units");
    ppEBEB_new->Draw("p");
    ppEBEB_old->Draw("E2 same");
    ppEBEB_new->SetTitle("1d projection of charged PF isolation in EBEB");
//	leg->AddEntry(ppEBEB_new,"#gamma #gamma CMSSW 7_6 rereco","lp")  ;
//    leg->AddEntry(ppEBEB_old,"#gamma #gamma CMSSW 7_4 prompt","f") ;
//    leg->AddEntry(ppEBEB_new,"#gamma f CMSSW 7_6 rereco","lp")  ;
// 	leg->AddEntry(ppEBEB_old,"#gamma f CMSSW 7_4 prompt","f") ;
    leg->AddEntry(ppEBEB_new,"f f CMSSW 7_6 rereco","lp")  ;
    leg->AddEntry(ppEBEB_old,"f f CMSSW 7_4 prompt","f") ;
    leg->Draw();
    canvEBEB->cd(2);
    TH1D* denominator=(TH1D*)ppEBEB_old->Clone("denominator");
    TH1D* ratios=(TH1D*)ppEBEB_new->Clone("ratio");
    ratios->Divide(denominator);
	ratios->SetTitle("");
    ratios->GetXaxis()->SetTitle("Bin");
    ratios->GetYaxis()->SetTitle("CMSSW_7_6/CMSSW_7_4");
    ratios->GetYaxis()->SetTitleSize(ppEBEB_new->GetYaxis()->GetTitleSize() * 5.0/3.0 );
    ratios->GetYaxis()->SetLabelSize(ppEBEB_new->GetYaxis()->GetLabelSize() *  7.0/3.0 );
    ratios->GetYaxis()->SetTitleOffset(ppEBEB_new->GetYaxis()->GetTitleOffset() *  4.0/7.0 );
    ratios->GetXaxis()->SetTitleOffset(ratios->GetXaxis()->GetTitleOffset() *7.8/7.0);
    ratios->GetXaxis()->SetLabelSize(ratios->GetXaxis()->GetLabelSize() *  7.0/3.0 );
    ratios->GetXaxis()->SetTitleSize( ratios->GetYaxis()->GetTitleSize() * 4.0/3.0 );
    ratios->GetXaxis()->SetLabelSize( ratios->GetYaxis()->GetLabelSize()  );
    ratios->GetYaxis()->SetNdivisions(505);
    ratios->Draw();
    ratios->GetYaxis()->SetTitle("Arbitrary Units");
    canvEBEB->cd(1);
    double margin = gPad->GetBottomMargin()+gPad->GetTopMargin();
    gPad->SetBottomMargin(0.2*margin);
    canvEBEB->cd(2);
    double margin2 = gPad->GetBottomMargin()+gPad->GetTopMargin();
    gPad->SetBottomMargin(1.8*margin2);
    gPad->SetTopMargin(0.25*margin2);
                
	canvEBEB->SaveAs(Form("/afs/cern.ch/user/m/mquittna/www/diphoton/moriond16/bkg_decomposition_moriond16v1_sync_v4_data/%s.png", canvEBEB->GetName()));
//	canvEBEB->SaveAs(Form("/afs/cern.ch/user/m/mquittna/www/diphoton/moriond16/bkg_decomposition_moriond16v1_sync_v5/%s.png", canvEBEB->GetName()));
//	canvEBEB->SaveAs(Form("/afs/cern.ch/user/m/mquittna/www/diphoton/moriond16/bkg_decomposition_moriond16v1_sync_v4_data/%s_800_12999.png", canvEBEB->GetName()));
	//canvEBEB->SaveAs(Form("/afs/cern.ch/user/m/mquittna/www/diphoton/moriond16/bkg_decomposition_moriond16v1_sync_v5/%s_800_12999.png", canvEBEB->GetName()));
	//////////////////////////////////////
    canvEBEE->Divide(1,2);
    canvEBEE->cd(1);
    gPad->SetPad(0., 0.3, 1., 1.0);
    gPad->SetLogy();
    canvEBEE->cd(2);
    gPad->SetPad(0., 0.0, 1.,0.3);
    canvEBEE->cd(1);
    ppEBEE_new->SetTitle("1d projection of charged PF isolation in EBEE");
    ppEBEE_new->GetYaxis()->SetRangeUser(1e-5,3);
	ppEBEE_new->SetLineColor(kBlack);
	ppEBEE_new->SetMarkerColor(kBlack);
	ppEBEE_new->SetMarkerSize(1.3);
	ppEBEE_new->SetLineWidth(2);
    ppEBEE_new->GetYaxis()->SetTitle("Arbitrary Units");
	ppEBEE_new->Draw("p");
	ppEBEE_old->SetFillColor(kRed);
	ppEBEE_old->SetFillStyle(3002);
	ppEBEE_old->Draw("E2 same");
	leg->Draw();
    canvEBEE->cd(2);
    TH1D* denominator2=(TH1D*)ppEBEE_old->Clone("denominator2");
    TH1D* ratios2=(TH1D*)ppEBEE_new->Clone("ratio2");
    ratios2->Divide(denominator2);
	ratios2->SetTitle("");
    ratios2->GetXaxis()->SetTitle("Bin");
    ratios2->GetYaxis()->SetTitle("CMSSW_7_6/CMSSW_7_4");
    ratios2->GetYaxis()->SetTitleSize(ppEBEE_new->GetYaxis()->GetTitleSize() * 5.0/3.0 );
    ratios2->GetYaxis()->SetLabelSize(ppEBEE_new->GetYaxis()->GetLabelSize() *  7.0/3.0 );
    ratios2->GetYaxis()->SetTitleOffset(ppEBEE_new->GetYaxis()->GetTitleOffset() *  4.0/7.0 );
    ratios2->GetXaxis()->SetTitleOffset(ratios2->GetXaxis()->GetTitleOffset() *7.8/7.0);
    ratios2->GetXaxis()->SetLabelSize(ratios2->GetXaxis()->GetLabelSize() *  7.0/3.0 );
    ratios2->GetXaxis()->SetTitleSize( ratios2->GetYaxis()->GetTitleSize() * 4.0/3.0 );
    ratios2->GetXaxis()->SetLabelSize( ratios2->GetYaxis()->GetLabelSize()  );
    ratios2->GetYaxis()->SetNdivisions(505);
    ratios2->Draw();
    ratios2->GetYaxis()->SetTitle("Arbitrary Units");
    canvEBEE->cd(1);
    double margin3 = gPad->GetBottomMargin()+gPad->GetTopMargin();
    gPad->SetBottomMargin(0.2*margin3);
    canvEBEE->cd(2);
    double margin4 = gPad->GetBottomMargin()+gPad->GetTopMargin();
    gPad->SetBottomMargin(1.8*margin4);
    gPad->SetTopMargin(0.25*margin4);
//canvEBEE->SaveAs(Form("/afs/cern.ch/user/m/mquittna/www/diphoton/moriond16/bkg_decomposition_moriond16v1_sync_v5/%s.png", canvEBEE->GetName()));
	canvEBEE->SaveAs(Form("/afs/cern.ch/user/m/mquittna/www/diphoton/moriond16/bkg_decomposition_moriond16v1_sync_v4_data/%s.png", canvEBEE->GetName()));
//	canvEBEE->SaveAs(Form("/afs/cern.ch/user/m/mquittna/www/diphoton/moriond16/bkg_decomposition_moriond16v1_sync_v4_data/%s_800_12999.png", canvEBEE->GetName()));
//	canvEBEE->SaveAs(Form("/afs/cern.ch/user/m/mquittna/www/diphoton/moriond16/bkg_decomposition_moriond16v1_sync_v4_data/%s_800_12999.png", canvEBEE->GetName()));
//	canvEBEE->SaveAs(Form("/afs/cern.ch/user/m/mquittna/www/diphoton/moriond16/bkg_decomposition_moriond16v1_sync_v5/%s_800_12999.png", canvEBEE->GetName()));
}

	    
