#./templates_maker.py --input-dir=output2dIDv2_selv2/ -o templatesdataMCIDv2_selv2.root --prepare-nosignal --only-subset="2D" --load templates_maker.json,templates_maker_prepare.json
#./templates_maker.py --input-dir=outputSinglePhoIDv2_selv2/ -o templatesdataMCSinglePhoIDv2_selv2.root --prepare-nosignal --only-subset="singlePho" --load templates_maker.json,templates_maker_prepare.json
#./templates_maker.py --load templates_maker_prepare.json,templates_maker.json --read-ws templatesdataMCSinglePhoIDv2_selv2.root,templatesdataMCIDv2_selv2.root --mix-templates --store-new-only -o mix25nsdataMCv2_selv2.root

#./templates_maker.py --load templates_maker_fits.json --read-ws old25ns0910/templatesdataMCIDv2_selv1.root,old25ns0910/mix25nsdatav2_selv1.root,fitteddataIDv2_selv1_4b_test2.root,fitdataIDv2_selv1_4b_test2.root -O /afs/cern.ch/user/m/mquittna/www/diphoton/template_studies_runD_v2/selv1_4b_test2/ -o purity_dataIDv2_selv1_2comp_4b_test2.root --plot-purity --plot-closure template_mix --plot-purityvalue fraction

#./templates_fitter.py --load templates_fitter.json --read-ws templatesdataMCIDv2_selv2.root,mix25nsdataMCv2_selv2.root -O /afs/cern.ch/user/m/mquittna/www/diphoton/template_studies_runD_v2/selv2_9b_mc/ -o fitdataIDv2_selv2_9b_mc.root --compare-templates --fit-massbins 3,3,0 --template-binning="0.0,0.1,5.0,15.0" --store-new-only
#./templates_fitter.py --load templates_fitter.json --read-ws templatesdataMCIDv2_selv2.root,mix25nsdataMCv2_selv2.root,fitdataIDv2_selv2_9b.root -O /afs/cern.ch/user/m/mquittna/www/diphoton/template_studies_runD_v2/selv2_9b/ -o fitteddataIDv2_selv1_9b.root --nominal-fit --fit-massbins 3,3,0  --template-binning="0.0,0.1,5.0,15.0" --fit-template unrolled_template_mix --store-new-only
#./templates_fitter.py --load templates_fitter.json --read-ws templatesdataMCIDv2_selv2.root,mix25nsdataMCv2_selv2.root,fitdataIDv2_selv2_9b_mc.root -O /afs/cern.ch/user/m/mquittna/www/diphoton/template_studies_runD_v2/selv2_9b_mc/ -o fitteddataIDv2_selv1_9b_mctruth.root --nominal-fit --fit-massbins 3,3,0  --template-binning="0.0,0.1,5.0,15.0" --fit-template unrolled_mctruth --store-new-only

#./templates_maker.py --load templates_maker_fits.json --read-ws templatesdataMCIDv2_selv2.root,mix25nsdatav2_selv2.root,fitteddataIDv2_selv2_9b.root,fitdataIDv2_selv2_9b.root -O /afs/cern.ch/user/m/mquittna/www/diphoton/template_studies_runD_v2/selv2_9b/ -o purity_dataIDv2_selv2_2comp_9b.root --plot-purity --plot-closure template_mix --plot-purityvalue fraction


# mc closure
#./templates_maker.py --load templates_maker_prepare.json,templates_maker00112003.json --read-ws templatesSinglePho00112003.root,templatesIDv2_selv2_00112003.root --mix-templates --mix-mc  --store-new-only -o mix25nsdataMCv2_selv2_00112003_2.root

#./templates_fitter.py --load templates_fitter.json --read-ws templatesdataMCIDv2_selv2.root,mix25nsdataMCv2_selv2.root -O /afs/cern.ch/user/m/mquittna/www/diphoton/template_studies_runD_v2/selv2_9b_mc/ -o fitIDv2_selv2_9b.root --compare-templates --fit-massbins 3,3,0 --template-binning="0.0,0.1,5.0,15.0" --store-new-only
#./templates_fitter.py --load templates_fitter.json --read-ws templatesdataMCIDv2_selv2.root,mix25nsdataMCv2_selv2.root,fitIDv2_selv2_9b.root -O /afs/cern.ch/user/m/mquittna/www/diphoton/template_studies_runD_v2/selv2_9b_mc/ -o fittedmcIDv2_selv2_9b_mc.root --nominal-fit --fit-massbins 3,3,0  --template-binning="0.0,0.1,5.0,15.0" --fit-template unrolled_template_mix --store-new-only --fit-mc
#./templates_fitter.py --load templates_fitter.json --read-ws templatesdataMCIDv2_selv2.root,mix25nsdataMCv2_selv2.root,fitIDv2_selv2_9b.root -O /afs/cern.ch/user/m/mquittna/www/diphoton/template_studies_runD_v2/selv2_9b_mc/ -o fittedmcIDv2_selv2_9b_mctruth.root --nominal-fit --fit-massbins 3,3,0  --template-binning="0.0,0.1,5.0,15.0" --fit-template unrolled_mctruth --store-new-only --fit-mc
#./templates_fitter.py --load templates_fitter.json --fit-mc --read-ws templatesdataMCIDv2_selv2.root,fittedmcIDv2_selv2_9b_mc.root,fittedmcIDv2_selv2_9b_mctruth.root,fitIDv2_selv2_9b.root -O /afs/cern.ch/user/m/mquittna/www/diphoton/template_studies_runD_v2/selv2_9b_mc/ -o purity_mc.root --plot-purity --plot-closure template_mix --plot-purityvalue fraction

#./templates_fitter.py --load templates_fitter.json --read-ws templatesdataMCIDv2_selv2.root,mix25nsdataMCv2_selv2.root,fitIDv2_selv2_9b.root -O /afs/cern.ch/user/m/mquittna/www/diphoton/template_studies_runD_v2/selv2_9b_00112003_data/ -o fittedmcIDv2_selv2_9b_00112003_data.root --nominal-fit --fit-massbins 3,3,0  --template-binning="0.0,0.1,5.0,15.0" --fit-template unrolled_template_mix --store-new-only

#./templates_fitter.py --load templates_fitter.json --read-ws templatesIDv2_selv2_00112003.root,mix25nsdataMCv2_selv2_00112003.root -O /afs/cern.ch/user/m/mquittna/www/diphoton/template_studies_runD_v2/selv2_9b_00112003/ -o fitIDv2_selv2_9b_00112003.root --compare-templates --fit-massbins 3,3,0 --template-binning="0.0,0.1,5.0,15.0" --store-new-only
#./templates_fitter.py --load templates_fitter.json --read-ws templatesIDv2_selv2_00112003.root,mix25nsdataMCv2_selv2_00112003.root,fitIDv2_selv2_9b_00112003.root -O /afs/cern.ch/user/m/mquittna/www/diphoton/template_studies_runD_v2/selv2_9b_00112003/ -o fittedmcIDv2_selv2_9b_00112003.root --nominal-fit --fit-massbins 3,3,0  --template-binning="0.0,0.1,5.0,15.0" --fit-template unrolled_template_mix --store-new-only --fit-mc
#./templates_fitter.py --load templates_fitter.json --read-ws templatesIDv2_selv2_00112003.root,mix25nsdataMCv2_selv2_00112003.root,fitIDv2_selv2_9b_00112003.root -O /afs/cern.ch/user/m/mquittna/www/diphoton/template_studies_runD_v2/selv2_9b_00112003/ -o fittedmcIDv2_selv2_9b_00112003_mctruth.root --nominal-fit --fit-massbins 3,3,0  --template-binning="0.0,0.1,5.0,15.0" --fit-template unrolled_mctruth --store-new-only --fit-mc
#./templates_fitter.py --load templates_fitter.json --fit-mc --read-ws templatesIDv2_selv2_00112003.root,fittedmcIDv2_selv2_9b_00112003.root,fittedmcIDv2_selv2_9b_00112003_mctruth.root,fitIDv2_selv2_9b_00112003.root -O /afs/cern.ch/user/m/mquittna/www/diphoton/template_studies_runD_v2/selv2_9b_00112003/ -o purity_00112003.root --plot-purity --plot-closure template_mix --plot-purityvalue fraction

#./templates_maker.py --input-dir=outputSinglePhoIDv2_selv1/ -o templatesdataMCSinglePhoIDv2_selv1.root --prepare-nosignal --only-subset="singlePho" --load templates_maker.json,templates_maker_fits.json
#./templates_maker.py --input-dir=output2dIDv2_selv1/ -o templatesdataMCIDv2_selv1.root --prepare-nosignal --only-subset="2D" --load templates_maker.json,templates_maker_fits.jso
#./templates_maker.py --load templates_maker_fits.json,templates_maker.json --read-ws templatesdataMCSinglePhoIDv2_selv1.root,templatesdataMCIDv2_selv1.root --mix-templates --store-new-only -o mix25nsdatav2_selv1.root
#./templates_fitter.py --load templates_fitter.json --read-ws templatesdataMCIDv2_selv2.root,mix25nsdataMCv2_selv2.root -O /afs/cern.ch/user/m/mquittna/www/diphoton/template_studies_runD_v2/selv2_4b_mc/ -o fitdataIDv2_selv2_4b_mc.root --compare-templates --fit-massbins 3,3,0 --template-binning="0.0,5.0,15.0" --store-new-only
#./templates_fitter.py --load templates_fitter.json --read-ws templatesdataMCIDv2_selv2.root,mix25nsdataMCv2_selv2.root,fitdataIDv2_selv2_4b.root -O /afs/cern.ch/user/m/mquittna/www/diphoton/template_studies_runD_v2/selv2_4b/ -o fitteddataIDv2_selv1_4b.root --nominal-fit --fit-massbins 3,3,0  --template-binning="0.0,5.0,15.0" --fit-template unrolled_template_mix --store-new-only
#./templates_fitter.py --load templates_fitter.json --read-ws templatesdataMCIDv2_selv2.root,mix25nsdataMCv2_selv2.root,fitdataIDv2_selv2_4b_mc.root -O /afs/cern.ch/user/m/mquittna/www/diphoton/template_studies_runD_v2/selv2_4b_mc/ -o fitteddataIDv2_selv1_4b_mctruth.root --nominal-fit --fit-massbins 3,3,0  --template-binning="0.0,5.0,15.0" --fit-template unrolled_mctruth --store-new-only
#./templates_maker.py --load templates_maker_fits.json --read-ws templatesdataMCIDv2_selv2.root,mix25nsdatav2_selv2.root,fitteddataIDv2_selv2_4b.root,fitdataIDv2_selv2_4b.root -O /afs/cern.ch/user/m/mquittna/www/diphoton/template_studies_runD_v2/selv2_4b/ -o purity_dataIDv2_selv2_2comp_4b.root --plot-purity --plot-closure template_mix --plot-purityvalue fraction
#./templates_fitter.py --load templates_fitter.json --read-ws templatesdataMCIDv2_selv1.root,mix25nsdataMCv2_selv1.root -O /afs/cern.ch/user/m/mquittna/www/diphoton/template_studies_runD_v2/selv1dataMC_9b/ -o fitdataMCIDv2_selv1_9b.root --compare-templates --fit-massbins 3,3,0 --template-binning="0.0,0.1,5.0,15.0" --store-new-only

#./templates_fitter.py --load templates_fitter.json --read-ws templatesdataMCIDv2_selv1.root,mix25nsdataMCv2_selv1.root,fitdataMCIDv2_selv1_9b.root -O /afs/cern.ch/user/m/mquittna/www/diphoton/template_studies_runD_v2/selv1dataMC_9b/ -o fitteddataMCIDv2_selv1_9b.root --nominal-fit --fit-massbins 3,3,0  --template-binning="0.0,0.1,5.0,15.0" --fit-template unrolled_template_mix --store-new-only
#./templates_fitter.py --load templates_fitter.json --read-ws templatesdataMCIDv2_selv1.root,mix25nsdataMCv2_selv1.root,fitdataMCIDv2_selv1_9b.root -O /afs/cern.ch/user/m/mquittna/www/diphoton/template_studies_runD_v2/selv1dataMC_9b/ -o fitteddataMCIDv2_selv1_9b2.root --nominal-fit --fit-massbins 3,3,0  --template-binning="0.0,0.1,5.0,15.0" --fit-template unrolled_template_mix --store-new-only
#./templates_fitter.py --load templates_fitter.json --read-ws templatesdataMCIDv2_selv1.root,mix25nsdataMCv2_selv1.root,fitdataMCIDv2_selv1_9b.root -O /afs/cern.ch/user/m/mquittna/www/diphoton/template_studies_runD_v2/selv1dataMC_9b/ -o fitteddataMCIDv2_selv1_9b3.root --nominal-fit --fit-massbins 3,3,0  --template-binning="0.0,0.1,5.0,15.0" --fit-template unrolled_mctruth --store-new-only

#./templates_fitter.py --load templates_fitter.json --read-ws templatesdataMCIDv2_selv1.root,mix25nsdataMCv2_selv1.root,fitteddataMCIDv2_selv1_9b.root,fitteddataMCIDv2_selv1_9b2.root,fitteddataMCIDv2_selv1_9b3.root,fitdataMCIDv2_selv1_9b.root -O /afs/cern.ch/user/m/mquittna/www/diphoton/template_studies_runD_v2/selv1dataMC_9b/ -o purity_dataIDv2_selv1_2comp_9b_all.root --plot-purity --plot-closure template_mix --plot-purityvalue fraction




