#./templates_maker.py --input-dir=output2dIDv2_selv1/ -o templatesdataMCIDv2_selv1.root --prepare-nosignal --only-subset="2D" --load templates_maker.json,templates_maker_fits.json

#./templates_maker.py --input-dir=outputSinglePhoIDv2_selv1/ -o templatesdataMCSinglePhoIDv2_selv1.root --prepare-nosignal --only-subset="singlePho" --load templates_maker.json,templates_maker_fits.json
#./templates_maker.py --load templates_maker_fits.json,templates_maker.json --read-ws templatesdataSinglePhoIDv2_selv1.root,templatesdataMCIDv2_selv1.root --mix-templates --store-new-only -o mix25nsdatav2_selv1.root
./templates_maker.py --load templates_maker_fits.json --read-ws templatesdataMCIDv2_selv1.root,mix25nsdatav2_selv1.root -O /afs/cern.ch/user/m/mquittna/www/diphoton/template_studies_runD_v2/selv1_4b/ -o fitdataIDv2_selv1_4b.root --compare-templates --fit-massbins 3,3,0 --template-binning="0.0,5.0,15.0" --store-new-only
./templates_maker.py --load templates_maker_fits.json --read-ws templatesdataMCIDv2_selv1.root,mix25nsdatav2_selv1.root,fitdataIDv2_selv1_4b.root -O /afs/cern.ch/user/m/mquittna/www/diphoton/template_studies_runD_v2/selv1_4b/ -o fitteddataIDv2_selv1_4b.root --nominal-fit --fit-massbins 3,3,0  --template-binning="0.0,5.0,15.0" --fit-template unrolled_template_mix --store-new-only
./templates_maker.py --load templates_maker_fits.json --read-ws templatesdataMCIDv2_selv1.root,mix25nsdatav2_selv1.root,fitteddataIDv2_selv1_4b.root,fitdataIDv2_selv1_4b.root -O /afs/cern.ch/user/m/mquittna/www/diphoton/template_studies_runD_v2/selv1_4b/ -o purity_dataIDv2_selv1_2comp_4b.root --plot-purity --plot-closure template_mix --plot-purityvalue fraction
./templates_maker.py --load templates_maker_fits.json --read-ws templatesdataMCIDv2_selv1.root,mix25nsdatav2_selv1.root -O /afs/cern.ch/user/m/mquittna/www/diphoton/template_studies_runD_v2/selv1_9b/ -o fitdataIDv2_selv1_9b.root --compare-templates --fit-massbins 3,3,0 --template-binning="0.0,0.1,5.0,15.0" --store-new-only
./templates_maker.py --load templates_maker_fits.json --read-ws templatesdataMCIDv2_selv1.root,mix25nsdatav2_selv1.root,fitdataIDv2_selv1_9b.root -O /afs/cern.ch/user/m/mquittna/www/diphoton/template_studies_runD_v2/selv1_9b/ -o fitteddataIDv2_selv1_9b.root --nominal-fit --fit-massbins 3,3,0  --template-binning="0.0,0.1,5.0,15.0" --fit-template unrolled_template_mix --store-new-only
./templates_maker.py --load templates_maker_fits.json --read-ws templatesdataMCIDv2_selv1.root,mix25nsdatav2_selv1.root,fitteddataIDv2_selv1_9b.root,fitdataIDv2_selv1_9b.root -O /afs/cern.ch/user/m/mquittna/www/diphoton/template_studies_runD_v2/selv1_9b/ -o purity_dataIDv2_selv1_2comp_9b.root --plot-purity --plot-closure template_mix --plot-purityvalue fraction
