#./templates_maker.py --input-dir=output2dIDv2_selv2/ -o templatesdataMCIDv2_selv12.root --prepare-nosignal --only-subset="2D" --load templates_maker.json,templates_maker_prepare.json

#./templates_maker.py --input-dir=outputSinglePhoIDv2_selv2/ -o templatesdataMCSinglePhoIDv2_selv2.root --prepare-nosignal --only-subset="singlePho" --load templates_maker.json,templates_maker_prepare.json
./templates_maker.py --load templates_maker_prepare.json,templates_maker.json --read-ws templatesdataMCSinglePhoIDv2_selv2.root,templatesdataMCIDv2_selv2.root --mix-templates --store-new-only -o mix25nsdataMCv2_selv2.root
#./templates_maker.py --load templates_maker_fits.json --read-ws old25ns0910/templatesdataMCIDv2_selv1.root,old25ns0910/mix25nsdatav2_selv1.root -O /afs/cern.ch/user/m/mquittna/www/diphoton/template_studies_runD_v2/selv1_4b_test2/ -o fitdataIDv2_selv1_4b_test2.root --compare-templates --fit-massbins 3,3,0 --template-binning="0.0,5.0,15.0" --store-new-only
#./templates_maker.py --load templates_maker_fits.json --read-ws old25ns0910/templatesdataMCIDv2_selv1.root,old25ns0910/mix25nsdatav2_selv1.root,fitdataIDv2_selv1_4b_test2.root -O /afs/cern.ch/user/m/mquittna/www/diphoton/template_studies_runD_v2/selv1_4b_test2/ -o fitteddataIDv2_selv1_4b_test2.root --nominal-fit --fit-massbins 3,3,0  --template-binning="0.0,5.0,15.0" --fit-template unrolled_template_mix --store-new-only

#./templates_maker.py --load templates_maker_fits.json --read-ws old25ns0910/templatesdataMCIDv2_selv1.root,old25ns0910/mix25nsdatav2_selv1.root,fitteddataIDv2_selv1_4b_test2.root,fitdataIDv2_selv1_4b_test2.root -O /afs/cern.ch/user/m/mquittna/www/diphoton/template_studies_runD_v2/selv1_4b_test2/ -o purity_dataIDv2_selv1_2comp_4b_test2.root --plot-purity --plot-closure template_mix --plot-purityvalue fraction

#./templates_fitter.py --load templates_fitter.json --read-ws templatesdataMCIDv2_selv2.root,mix25nsdataMCv2_selv2.root -O /afs/cern.ch/user/m/mquittna/www/diphoton/template_studies_runD_v2/selv2_9b_mc/ -o fitdataIDv2_selv2_9b_mc.root --compare-templates --fit-massbins 3,3,0 --template-binning="0.0,0.1,5.0,15.0" --store-new-only
./templates_fitter.py --load templates_fitter.json --read-ws templatesdataMCIDv2_selv2.root,mix25nsdataMCv2_selv2.root,fitdataIDv2_selv2_9b.root -O /afs/cern.ch/user/m/mquittna/www/diphoton/template_studies_runD_v2/selv2_9b/ -o fitteddataIDv2_selv1_9b.root --nominal-fit --fit-massbins 3,3,0  --template-binning="0.0,0.1,5.0,15.0" --fit-template unrolled_template_mix --store-new-only
#./templates_fitter.py --load templates_fitter.json --read-ws templatesdataMCIDv2_selv2.root,mix25nsdataMCv2_selv2.root,fitdataIDv2_selv2_9b_mc.root -O /afs/cern.ch/user/m/mquittna/www/diphoton/template_studies_runD_v2/selv2_9b_mc/ -o fitteddataIDv2_selv1_9b_mctruth.root --nominal-fit --fit-massbins 3,3,0  --template-binning="0.0,0.1,5.0,15.0" --fit-template unrolled_mctruth --store-new-only

#./templates_maker.py --load templates_maker_fits.json --read-ws templatesdataMCIDv2_selv2.root,mix25nsdatav2_selv2.root,fitteddataIDv2_selv2_9b.root,fitdataIDv2_selv2_9b.root -O /afs/cern.ch/user/m/mquittna/www/diphoton/template_studies_runD_v2/selv2_9b/ -o purity_dataIDv2_selv2_2comp_9b.root --plot-purity --plot-closure template_mix --plot-purityvalue fraction


# mc closure
#./templates_maker.py --load templates_maker.json,templates_maker_fits_closure.json -o closure.root --input-dir=output2dIDv2_selv1/ --prepare-nosignal --only-subset="2D"
#./templates_maker.py --load templates_maker_fits_closure.json --read-ws closure.root -O /afs/cern.ch/user/m/mquittna/www/diphoton/template_studies_runD_v2/selv1_4b_mcclosure/ -o closure24b.root --compare-templates --fit-massbins 3,3,0  --store-new-only --template-binning="0.0,5.0,15.0"
#./templates_maker.py --load templates_maker_fits_closure.json --read-ws closure.root,closure24b.root -O /afs/cern.ch/user/m/mquittna/www/diphoton/template_studies_runD_v2/selv1_4b_mcclosure/ -o closure34b.root --nominal-fit --fit-massbins 3,3,0  --template-binning="0.0,5.0,15.0" --fit-template unrolled_mctruth --store-new-only
#./templates_maker.py --load templates_maker_fits_closure.json --read-ws closure.root,closure24b.root,closure34b.root -O /afs/cern.ch/user/m/mquittna/www/diphoton/template_studies_runD_v2/selv1_4b_mcclosure/ -o closure44b.root --plot-purity --plot-closure mctruth --plot-purityvalue fraction

#./templates_maker.py --input-dir=outputSinglePhoIDv2_selv1/ -o templatesdataMCSinglePhoIDv2_selv1.root --prepare-nosignal --only-subset="singlePho" --load templates_maker.json,templates_maker_fits.json
#./templates_maker.py --input-dir=output2dIDv2_selv1/ -o templatesdataMCIDv2_selv1.root --prepare-nosignal --only-subset="2D" --load templates_maker.json,templates_maker_fits.jso
#./templates_maker.py --load templates_maker_fits.json,templates_maker.json --read-ws templatesdataMCSinglePhoIDv2_selv1.root,templatesdataMCIDv2_selv1.root --mix-templates --store-new-only -o mix25nsdatav2_selv1.root
#./templates_fitter.py --load templates_fitter.json --read-ws templatesdataMCIDv2_selv2.root,mix25nsdataMCv2_selv2.root -O /afs/cern.ch/user/m/mquittna/www/diphoton/template_studies_runD_v2/selv2_4b_mc/ -o fitdataIDv2_selv2_4b_mc.root --compare-templates --fit-massbins 3,3,0 --template-binning="0.0,5.0,15.0" --store-new-only
./templates_fitter.py --load templates_fitter.json --read-ws templatesdataMCIDv2_selv2.root,mix25nsdataMCv2_selv2.root,fitdataIDv2_selv2_4b.root -O /afs/cern.ch/user/m/mquittna/www/diphoton/template_studies_runD_v2/selv2_4b/ -o fitteddataIDv2_selv1_4b.root --nominal-fit --fit-massbins 3,3,0  --template-binning="0.0,5.0,15.0" --fit-template unrolled_template_mix --store-new-only
#./templates_fitter.py --load templates_fitter.json --read-ws templatesdataMCIDv2_selv2.root,mix25nsdataMCv2_selv2.root,fitdataIDv2_selv2_4b_mc.root -O /afs/cern.ch/user/m/mquittna/www/diphoton/template_studies_runD_v2/selv2_4b_mc/ -o fitteddataIDv2_selv1_4b_mctruth.root --nominal-fit --fit-massbins 3,3,0  --template-binning="0.0,5.0,15.0" --fit-template unrolled_mctruth --store-new-only
#./templates_maker.py --load templates_maker_fits.json --read-ws templatesdataMCIDv2_selv2.root,mix25nsdatav2_selv2.root,fitteddataIDv2_selv2_4b.root,fitdataIDv2_selv2_4b.root -O /afs/cern.ch/user/m/mquittna/www/diphoton/template_studies_runD_v2/selv2_4b/ -o purity_dataIDv2_selv2_2comp_4b.root --plot-purity --plot-closure template_mix --plot-purityvalue fraction
#./templates_fitter.py --load templates_fitter.json --read-ws templatesdataMCIDv2_selv1.root,mix25nsdataMCv2_selv1.root -O /afs/cern.ch/user/m/mquittna/www/diphoton/template_studies_runD_v2/selv1dataMC_9b/ -o fitdataMCIDv2_selv1_9b.root --compare-templates --fit-massbins 3,3,0 --template-binning="0.0,0.1,5.0,15.0" --store-new-only

#./templates_fitter.py --load templates_fitter.json --read-ws templatesdataMCIDv2_selv1.root,mix25nsdataMCv2_selv1.root,fitdataMCIDv2_selv1_9b.root -O /afs/cern.ch/user/m/mquittna/www/diphoton/template_studies_runD_v2/selv1dataMC_9b/ -o fitteddataMCIDv2_selv1_9b.root --nominal-fit --fit-massbins 3,3,0  --template-binning="0.0,0.1,5.0,15.0" --fit-template unrolled_template_mix --store-new-only
#./templates_fitter.py --load templates_fitter.json --read-ws templatesdataMCIDv2_selv1.root,mix25nsdataMCv2_selv1.root,fitdataMCIDv2_selv1_9b.root -O /afs/cern.ch/user/m/mquittna/www/diphoton/template_studies_runD_v2/selv1dataMC_9b/ -o fitteddataMCIDv2_selv1_9b2.root --nominal-fit --fit-massbins 3,3,0  --template-binning="0.0,0.1,5.0,15.0" --fit-template unrolled_template_mix --store-new-only
#./templates_fitter.py --load templates_fitter.json --read-ws templatesdataMCIDv2_selv1.root,mix25nsdataMCv2_selv1.root,fitdataMCIDv2_selv1_9b.root -O /afs/cern.ch/user/m/mquittna/www/diphoton/template_studies_runD_v2/selv1dataMC_9b/ -o fitteddataMCIDv2_selv1_9b3.root --nominal-fit --fit-massbins 3,3,0  --template-binning="0.0,0.1,5.0,15.0" --fit-template unrolled_mctruth --store-new-only

#./templates_fitter.py --load templates_fitter.json --read-ws templatesdataMCIDv2_selv1.root,mix25nsdataMCv2_selv1.root,fitteddataMCIDv2_selv1_9b.root,fitteddataMCIDv2_selv1_9b2.root,fitteddataMCIDv2_selv1_9b3.root,fitdataMCIDv2_selv1_9b.root -O /afs/cern.ch/user/m/mquittna/www/diphoton/template_studies_runD_v2/selv1dataMC_9b/ -o purity_dataIDv2_selv1_2comp_9b_all.root --plot-purity --plot-closure template_mix --plot-purityvalue fraction

#./templates_maker.py --load templates_maker_fits.json --read-ws templatesdataMCIDv2_selv1.root,mix25nsdatav2_selv1.root -O /afs/cern.ch/user/m/mquittna/www/diphoton/template_studies_runD_v2/selv1_1mb_9b/ -o fitdataIDv2_selv1_1mb_9b.root --compare-templates --fit-massbins 1,1,0 --template-binning="0.0,0.1,5.0,15.0" --store-new-only
#./templates_maker.py --load templates_maker_fits.json --read-ws templatesdataMCIDv2_selv1.root,mix25nsdatav2_selv1.root,fitdataIDv2_selv1_1mb_9b.root -O /afs/cern.ch/user/m/mquittna/www/diphoton/template_studies_runD_v2/selv1_1mb_9b/ -o fitteddataIDv2_selv1_1mb_9b.root --nominal-fit --fit-massbins 1,1,0  --template-binning="0.0,0.1,5.0,15.0" --fit-template unrolled_template_mix --store-new-only
#./templates_maker.py --load templates_maker_fits.json --read-ws templatesdataMCIDv2_selv1.root,mix25nsdatav2_selv1.root,fitteddataIDv2_selv1_9b.root,fitdataIDv2_selv1_9b.root -O /afs/cern.ch/user/m/mquittna/www/diphoton/template_studies_runD_v2/selv1_9b/ -o purity_dataIDv2_selv1_2comp_9b.root --plot-purity --plot-closure template_mix --plot-purityvalue fraction



