#################prepare templates####################################
#./templates_maker.py --input-dir=/afs/cern.ch/user/m/musella/public/workspace/exo/full_analysis_spring16v1_sync_v4_cert_275125/  -o  templates_spring16v1_sync_v4_data.root  --prepare-data --only-subset="2D" --load templates_maker.json,templates_maker_prepare.json |tee output_template_data.txt
##for single and oduble SB
#./templates_maker.py --input-dir=/afs/cern.ch/user/s/spigazzi/work/public/Xgg/Spring16/double_pho_spring16v1_sync_v1/  -o  templates_spring16v1_sync_v1_simone_data.root  --prepare-data --only-subset="2D" --load templates_maker.json,templates_maker_prepare.json

#./templates_maker.py --input-dir=/afs/cern.ch/user/m/musella/public/workspace/exo/full_analysis_spring16v1_sync_v1_2705_cert/  -o  templates_spring16v1_sync_v4_mc.root --only-subset="2D" --prepare-mc --prepare-nosignal  --load templates_maker.json,templates_maker_prepare.json|tee output_template_mc.txt
wait
#hadd templates_spring16v1_sync_v4_geniso.root  templates_spring16v1_sync_v4_mc_geniso.root templates_spring16v1_sync_v4_data.root
wait
#reprocess single photon
#./templates_maker.py --input-dir=/mnt/t3nfs01/data01/shome/mquittna/CMSSW/EXO_8_0_8/src/diphotons/Analysis/config/singlePhoton_spring16_v1/  -o  templates_spring16v1_sync_v1_singlephoton.root --signals '{}'  --only-subset="singlePho" --load templates_maker.json,templates_maker_prepare.json
wait
#./templates_maker.py --load templates_maker_prepare.json,templates_maker.json --read-ws templates_spring16v1_sync_v1_singlephoton.root,templates_spring16v1_sync_v4_geniso.root --mix-templates --mix-mc --store-new-only -o mix_spring16v1_sync_v4_geniso.root
#./templates_maker.py --load templates_maker_prepare.json,templates_maker.json --read-ws templates_spring16v1_sync_v1_singlephoton.root,templates_spring16v1_sync_v4_geniso.root --mix-templates --store-new-only -o mix_spring16v1_sync_v4_geniso.root
################ compare templates#################################

##full mass range
##./templates_fitter.py --load templates_fitter.json,lumi.json --read-ws templates_spring16v1_sync_v4_mc_geniso.root,templates_spring16v1_sync_v4_data.root,mix_spring16v1_sync_v4_geniso_mc.root,mix_spring16v1_sync_v4_data.root  -O /afs/cern.ch/user/m/mquittna/www/diphoton/spring16/bkg_decomposition_spring16v1_sync_v4_geniso/ -o compared_spring16v1_sync_v1_geniso_fullmass.root --compare-templates --fit-massbins 1,1,0 --template-binning="0.0,0.1,5.0,15.0"  --store-new-only --lumi 4.0  --saveas pdf,convert_png,root
##./templates_fitter.py --load templates_fitter.json,lumi.json --read-ws templates_spring16v1_sync_v4_mc_nogeniso.root,templates_spring16v1_sync_v4_data.root,mix_spring16v1_sync_v4_nogeniso_mc.root,mix_spring16v1_sync_v4_data.root  -O /afs/cern.ch/user/m/mquittna/www/diphoton/spring16/bkg_decomposition_spring16v1_sync_v4_nogeniso/ -o compared_spring16v1_sync_v1_nogeniso_fullmass.root --compare-templates --fit-massbins 1,1,0 --template-binning="0.0,0.1,5.0,15.0"  --store-new-only --lumi 4.0  --saveas pdf,convert_png,root
##fixed mass bins
##./templates_fitter.py --load templates_fitter.json,lumi.json --read-ws templates_spring16v1_sync_v4_mc_geniso.root,templates_spring16v1_sync_v4_data.root,mix_spring16v1_sync_v4_geniso_mc.root,mix_spring16v1_sync_v4_data.root  -O /afs/cern.ch/user/m/mquittna/www/diphoton/spring16/bkg_decomposition_spring16v1_sync_v4_geniso/  -o compared_spring16v1_sync_v4_geniso.root --compare-templates --fixed-massbins --template-binning="0.0,0.1,5.0,15.0" --store-new-only --lumi 4.0   --saveas pdf,convert_png,root|tee output_comp_spring_v4_geniso.txt
##./templates_fitter.py --load templates_fitter.json,lumi.json --read-ws templates_spring16v1_sync_v4_mc_nogeniso.root,templates_spring16v1_sync_v4_data.root,mix_spring16v1_sync_v4_nogeniso_mc.root,mix_spring16v1_sync_v4_data.root  -O /afs/cern.ch/user/m/mquittna/www/diphoton/spring16/bkg_decomposition_spring16v1_sync_v4_nogeniso/  -o compared_spring16v1_sync_v4_nogeniso.root --compare-templates --fixed-massbins --template-binning="0.0,0.1,5.0,15.0" --store-new-only --lumi 4.0   --saveas pdf,convert_png,root|tee output_comp_spring_v4_nogeniso.txt

#################fits##################

###################3comp########################################
./templates_fitter.py --load templates_fitter.json,lumi.json --read-ws compared_spring16v1_sync_v4_geniso.root -O /afs/cern.ch/user/m/mquittna/www/diphoton/spring16/bkg_decomposition_spring16v1_sync_v4_geniso/  --purity-sigregion -o fitted_spring16v1_sync_v4_data.root --blind  --nominal-fit --fixed-massbins  --template-binning="0.0,0.1,5.0,15.0" --fit-template unrolled_template_mix --store-new-only --lumi  4.0 --saveas pdf,convert_png,root |tee output_fit_spring_v4_data.txt
#./templates_fitter.py --load templates_fitter.json,lumi.json --read-ws compared_spring16v1_sync_v4_geniso.root -O /afs/cern.ch/user/m/mquittna/www/diphoton/spring16/bkg_decomposition_spring16v1_sync_v4_geniso/  --purity-sigregion -o fitted_spring16v1_sync_v4_geniso_mc.root  --nominal-fit --fixed-massbins  --fit-mc --template-binning="0.0,0.1,5.0,15.0" --fit-template unrolled_template_mix --store-new-only --lumi  4.0 --saveas pdf,convert_png,root |tee output_fit_spring_v4_geniso_mc.txt
#./templates_fitter.py --load templates_fitter.json,lumi.json --read-ws compared_spring16v1_sync_v4_nogeniso.root -O /afs/cern.ch/user/m/mquittna/www/diphoton/spring16/bkg_decomposition_spring16v1_sync_v4_nogeniso/  --purity-sigregion -o fitted_spring16v1_sync_v4_nogeniso_mc.root  --nominal-fit --fixed-massbins  --fit-mc --template-binning="0.0,0.1,5.0,15.0" --fit-template unrolled_template_mix --store-new-only --lumi  4.0 --saveas pdf,convert_png,root |tee output_fit_spring_v4_nogeniso_mc.txt
###./templates_fitter.py --load templates_fitter.json,lumi.json --read-ws compared_spring16v1_sync_v4_geniso.root -O /afs/cern.ch/user/m/mquittna/www/diphoton/spring16/bkg_decomposition_spring16v1_sync_v4_geniso_fitToMC/  --purity-sigregion -o fitted_spring16v1_sync_v4_geniso_mc_fitToMC.root  --nominal-fit --fixed-massbins  --fit-mc --template-binning="0.0,0.1,5.0,15.0" --fit-template unrolled_template_mix --store-new-only --lumi  4.0 --saveas pdf,convert_png,root |tee output_fit_spring_v4_geniso_mc_fitToMC.txt
###./templates_fitter.py --load templates_fitter.json,lumi.json --read-ws compared_spring16v1_sync_v4_nogeniso.root -O /afs/cern.ch/user/m/mquittna/www/diphoton/spring16/bkg_decomposition_spring16v1_sync_v4_nogeniso_fitToMC/  --purity-sigregion -o fitted_spring16v1_sync_v4_nogeniso_mc_fitToMC.root  --nominal-fit --fixed-massbins  --fit-mc --template-binning="0.0,0.1,5.0,15.0" --fit-template unrolled_template_mix --store-new-only --lumi  4.0 --saveas pdf,convert_png,root |tee output_fit_spring_v4_nogeniso_mc_fitToMC.txt

#./templates_fitter.py --load templates_fitter.json,lumi.json --read-ws compared_spring16v1_sync_v4_geniso.root -O /afs/cern.ch/user/m/mquittna/www/diphoton/spring16/bkg_decomposition_spring16v1_sync_v4_geniso/  --purity-sigregion -o fitted_spring16v1_sync_v4_geniso_mctruth.root  --nominal-fit --fixed-massbins  --fit-mc --template-binning="0.0,0.1,5.0,15.0" --fit-template unrolled_mctruth --store-new-only --lumi  4.0 --saveas pdf,convert_png,root |tee output_fit_spring_v4_geniso_mctruth.txt
#./templates_fitter.py --load templates_fitter.json,lumi.json --read-ws compared_spring16v1_sync_v4_nogeniso.root -O /afs/cern.ch/user/m/mquittna/www/diphoton/spring16/bkg_decomposition_spring16v1_sync_v4_nogeniso/  --purity-sigregion -o fitted_spring16v1_sync_v4_nogeniso_mctruth.root  --nominal-fit --fixed-massbins  --fit-mc --template-binning="0.0,0.1,5.0,15.0" --fit-template unrolled_mctruth --store-new-only --lumi  4.0 --saveas pdf,convert_png,root |tee output_fit_spring_v4_nogeniso_mctruth.txt
##./templates_fitter.py --load templates_fitter.json,lumi.json --read-ws compared_spring16v1_sync_v4_nogeniso.root -O /afs/cern.ch/user/m/mquittna/www/diphoton/spring16/bkg_decomposition_spring16v1_sync_v4_nogeniso_fitToMC/  --purity-sigregion -o fitted_spring16v1_sync_v4_nogeniso_mctruth_fitToMC.root  --nominal-fit --fixed-massbins  --fit-mc --template-binning="0.0,0.1,5.0,15.0" --fit-template unrolled_mctruth --store-new-only --lumi  4.0 --saveas pdf,convert_png,root |tee output_fit_spring_v4_nogeniso_mctruth_fitToMC.txt
##./templates_fitter.py --load templates_fitter.json,lumi.json --read-ws compared_spring16v1_sync_v4_geniso.root -O /afs/cern.ch/user/m/mquittna/www/diphoton/spring16/bkg_decomposition_spring16v1_sync_v4_geniso_fitToMC/  --purity-sigregion -o fitted_spring16v1_sync_v4_geniso_mctruth_fitToMC.root  --nominal-fit --fixed-massbins  --fit-mc --template-binning="0.0,0.1,5.0,15.0" --fit-template unrolled_mctruth --store-new-only --lumi  4.0 --saveas pdf,convert_png,root |tee output_fit_spring_v4_geniso_mctruth_fitToMC.txt

############plot purity closure########################
#data
./templates_fitter.py --load templates_fitter.json,lumi.json --saveas pdf,convert_png,root --read-ws templates_spring16v1_sync_v4_data.root,compared_spring16v1_sync_v4_geniso.root,fitted_spring16v1_sync_v4_data.root,fitted_spring16v1_sync_v4_geniso_mctruth.root  -O /afs/cern.ch/user/m/mquittna/www/diphoton/spring16/bkg_decomposition_spring16v1_sync_v4_geniso/ --plot-purity --plot-closure template_mix --plot-purityvalue fraction  --lumi 4.0 --full-error  --store-new-only |tee output_fullregion_purity_spring_v4_geniso_data_mctruth.txt 
##mc closure
##./templates_fitter.py --load templates_fitter.json --saveas pdf,convert_png,root --read-ws templates_spring16v1_sync_v4_data.root,compared_spring16v1_sync_v4_geniso.root,fitted_spring16v1_sync_v4_geniso_mc_fitToMC.root,fitted_spring16v1_sync_v4_geniso_mctruth_fitToMC.root   -O /afs/cern.ch/user/m/mquittna/www/diphoton/spring16/bkg_decomposition_spring16v1_sync_v4_geniso_fitToMC/ --plot-purity --plot-closure template_mix --plot-purityvalue fraction --full-error -o purity_spring16v1_sync_v4_geniso_mc.root --fit-mc --store-new-only 
##./templates_fitter.py --load templates_fitter.json --saveas pdf,convert_png,root --read-ws templates_spring16v1_sync_v4_data.root,compared_spring16v1_sync_v4_nogeniso.root,fitted_spring16v1_sync_v4_nogeniso_mc_fitToMC.root,fitted_spring16v1_sync_v4_nogeniso_mctruth_fitToMC.root   -O /afs/cern.ch/user/m/mquittna/www/diphoton/spring16/bkg_decomposition_spring16v1_sync_v4_nogeniso_fitToMC/ --plot-purity --plot-closure template_mix --plot-purityvalue fraction --full-error -o purity_spring16v1_sync_v4_nogeniso_mc.root --fit-mc --store-new-only 


#sigregion
#data
./templates_fitter.py --load templates_fitter.json,lumi.json --saveas pdf,convert_png,root --read-ws templates_spring16v1_sync_v4_data.root,compared_spring16v1_sync_v4_geniso.root,fitted_spring16v1_sync_v4_data.root,fitted_spring16v1_sync_v4_geniso_mc.root,fitted_spring16v1_sync_v4_geniso_mctruth.root  -O /afs/cern.ch/user/m/mquittna/www/diphoton/spring16/bkg_decomposition_spring16v1_sync_v4_geniso/ --purity-sigregion --plot-purity --plot-closure template_mix --plot-purityvalue fraction  --lumi 4.0 --full-error  --store-new-only |tee output_sigregion_purity_spring_v4_data_mctruth.txt 
##MC closure
#./templates_fitter.py --load templates_fitter.json,lumi.json --saveas pdf,convert_png,root --read-ws templates_spring16v1_sync_v1_geniso.root,compared_spring16v1_sync_v1_geniso_unblind.root,fitted_spring16v1_sync_v1_geniso_mc_unblind.root,fitted_spring16v1_sync_v1_geniso_mctruth_unblind.root   -O /afs/cern.ch/user/m/mquittna/www/diphoton/spring16/test_with_morionddataset/ --plot-purity --purity-sigregion --plot-closure template_mix --plot-purityvalue fraction  --lumi 0.58 --full-error -o purity_sigregion_spring16v1_sync_v1_geniso_mc_unblind.root --fit-mc --store-new-only 
#./templates_fitter.py --load templates_fitter.json,lumi.json --saveas pdf,convert_png,root --read-ws templates_moriond16v1_sync_v5.root,compared_moriond16v1_sync_v5.root,fitted_moriond16v1_sync_v5_mc.root,fitted_moriond16v1_sync_v5_mctruth.root   -O /afs/cern.ch/user/m/mquittna/www/diphoton/spring16/test_with_morionddataset/ --plot-purity --purity-sigregion --plot-closure template_mix --plot-purityvalue fraction  --lumi 2.7 --full-error -o purity_test.root --fit-mc --store-new-only 
#./templates_fitter.py --load templates_fitter.json,lumi.json --saveas pdf,convert_png,root --read-ws templates_moriond16v1_sync_v5.root,compared_moriond16v1_sync_v5.root,fitted_moriond16v1_sync_v5_mc.root,fitted_moriond16v1_sync_v5_mctruth.root   -O /afs/cern.ch/user/m/mquittna/www/diphoton/spring16/test_with_morionddataset/ --plot-purity --purity-sigregion --plot-closure template_mix --plot-purityvalue fraction  --lumi 2.7 --full-error -o purity_test.root --store-new-only 



