{
TFile *f0 = TFile::Open("templates_spring16v1_sync_v5_singlephoton_data.root");
TFile *f1 = TFile::Open("templates_moriond16v1_sync_singlephoton_check.root");
//TFile *f0 = TFile::Open("templates_spring16v1_sync_v1_qcd_noweightcut_singlephoton.root");
//TFile *f1 = TFile::Open("templates_moriond16v1_sync_singlephoton_check.root");
f0->cd();
TLegend* leg= new TLegend(0.4,0.7,0.9,0.9);
//TLegend* leg= new TLegend(0.4,0.1,0.9,0.4);
TCanvas *c1=new TCanvas("c1","c1");
c1->Divide(1,2);
c1->cd(1);
gPad->SetPad(0., 0.3, 1., 1.0);
gPad->SetLogy();
c1->cd(2);
gPad->SetGridy();
gPad->SetPad(0., 0.0, 1.,0.3);
gStyle->SetOptStat(0);
double bins[10]={0.,0.1,1.0,3.0,5.0,7.0,9.0,11.0,13.0,15.0};
TH1F* hnew=new TH1F("hnew","hnew",9,bins);
TH1F* hnew2=new TH1F("hnew2","hnew2",9,bins);
TH1F* hnewC=new TH1F("hnewC","hnewC",9,bins);
TH1F* hnewC2=new TH1F("hnewC2","hnewC2",9,bins);
hnewC->SetLineColor(kRed);
hnew->GetXaxis()->SetTitle("chIso (GeV)");
hnew->SetLineColor(kGreen+1);
hnewC->SetLineStyle(kDashed);
//tree_template_f_singlePho_EE->Draw("phoPt>>hnew","","NORM");
//leg->AddEntry(hnew,"2016 data prompt EE","lp")  ;
c1->cd(1);
tree_template_f_singlePho_EE->Draw("templateNdim1Dim0>>hnew","","NORM");
cout << "sideband EE 2016: " <<  hnew->GetEntries() << endl;
tree_template_f_singlePho_EE->Draw("templateNdim1Dim0>>hnew2","phoPt >600.","goff");
cout << "sideband EE 2016, pt > 600 GeV: " <<  hnew2->GetEntries() << endl;
tree_template_f_singlePho_EE->Draw("templateNdim1Dim0>>hnewC","phoHoE*(phoPt)/(TMath::Min(127.,phoPt)) < 0.06","NORM SAME");
cout << "sideband EE 2016 + HoE cut: " <<  hnewC->GetEntries() << endl;
tree_template_f_singlePho_EE->Draw("templateNdim1Dim0>>hnewC2","(phoHoE*(phoPt)/(TMath::Min(127.,phoPt)) < 0.06)*(phoPt > 600.) ","goff");
cout << "sideband EE 2016 + HoE cut, pt > 600 GeV: " << hnewC2->GetEntries() << endl;
/*tree_template_mc_f_singlePho_EE->Draw("phoPt>>hnew","weight","goff");
cout << "sideband EE 2016: " <<  hnew->GetEntries() << endl;
cout << "weighted: " <<  hnew->Integral() << endl;

tree_template_mc_f_singlePho_EE->Draw("phoPt>>hnew2","(phoPt >600.)*weight","goff");
cout << "sideband EE 2016, pt > 600 GeV: " <<  hnew2->GetEntries() << endl;
cout << "weighted: " <<  hnew2->Integral() << endl;
tree_template_mc_f_singlePho_EE->Draw("phoPt>>hnewC","weight*(phoHoE*(phoPt)/(TMath::Min(127.,phoPt)) < 0.06) ","goff");
cout << "sideband EE 2016 + HoE cut: " << hnewC->GetEntries() << endl;
cout << "weighted: " <<  hnewC->Integral() << endl;
tree_template_mc_f_singlePho_EE->Draw("phoPt>>hnewC2","weight*(phoHoE*(phoPt)/(TMath::Min(127.,phoPt)) < 0.06)*(phoPt >600.) ","goff");
cout << "sideband EE 2016 + HoE cut, pt > 600 GeV: " << hnewC2->GetEntries() << endl;
cout << "weighted: " <<  hnewC2->Integral() << endl;
*/
leg->AddEntry(hnew,"2016 data sideband EE","lp")  ;
leg->AddEntry(hnewC,"2016 data sideband EE + HoE cut","lp")  ;
f1->cd();
TH1F* hold=new TH1F("hold","hold",9,bins);
TH1F* holdC=new TH1F("holdC","holdC",9,bins);
TH1F* hold2=new TH1F("hold2","hold2",9,bins);
TH1F* holdC2=new TH1F("holdC2","holdC2",9,bins);
hold->SetLineColor(kBlue+1);
holdC->SetLineColor(kCyan+1);
//hold->SetLineStyle(kDashed);
holdC->SetLineStyle(kDashed);
/*
tree_template_f_singlePho_EE->Draw("phoPt>>hold","","NORM SAME");
tree_template_f_singlePho_EE->Draw("phoPt>>holdC","phoHoE*(phoPt)/(TMath::Min(127.,phoPt)) < 0.06 ","NORM SAME");
leg->AddEntry(hold,"2015 data prompt EE","lp")  ;
leg->AddEntry(holdC,"2015 data prompt EE + H/E cut","lp")  ;
*/
tree_template_f_singlePho_EE->Draw("templateNdim1Dim0>>hold","","NORM SAME");
cout << "sideband EE 2015: " << hold->GetEntries() << endl;
tree_template_f_singlePho_EE->Draw("templateNdim1Dim0>>hold2","phoPt> 600.","goff");
cout << "sideband EE 2015, pt >600 GeV: " << hold2->GetEntries() << endl;
tree_template_f_singlePho_EE->Draw("templateNdim1Dim0>>holdC","(phoHoE*(phoPt)/(TMath::Min(127.,phoPt)) < 0.06) ","NORM SAME");
cout << "sideband EE 2015 + HoE cut: " << holdC->GetEntries() << endl;
tree_template_f_singlePho_EE->Draw("templateNdim1Dim0>>holdC2","(phoHoE*(phoPt)/(TMath::Min(127.,phoPt)) < 0.06)*(phoPt >600.) ","goff");
cout << "sideband EE 2015 + HoE cut, pt > 600 GeV: " << holdC2->GetEntries() << endl;
leg->AddEntry(holdC,"2015 data sideband EE + H/E cut","lp")  ;
leg->AddEntry(hold,"2015 data sideband EE","lp")  ;
leg->Draw();
c1->cd(2);
TH1D* denominatorn=(TH1D*)hnewC->Clone("denominatorn");
TH1D* ratiosn=(TH1D*)hnew->Clone("ration");
ratiosn->Divide(denominatorn);
TH1D* denominator=(TH1D*)holdC->Clone("denominator");
TH1D* ratios=(TH1D*)hold->Clone("ratio");
ratios->Divide(denominator);
ratios->SetTitle("");
ratios->GetXaxis()->SetTitle("Bin");
ratios->GetYaxis()->SetRangeUser(0.95,1.05);
ratios->GetYaxis()->SetTitle("15/15withcut");
ratios->GetYaxis()->SetTitleSize(hnew->GetYaxis()->GetTitleSize() * 5.0/3.0 );
ratios->GetYaxis()->SetLabelSize(hnew->GetYaxis()->GetLabelSize() *  7.0/3.0 );
ratios->GetYaxis()->SetTitleOffset(hnew->GetYaxis()->GetTitleOffset() *  4.0/7.0 );
ratios->GetXaxis()->SetTitleOffset(ratios->GetXaxis()->GetTitleOffset() *7.8/7.0);
ratios->GetXaxis()->SetLabelSize(ratios->GetXaxis()->GetLabelSize() *  7.0/3.0 );
ratios->GetXaxis()->SetTitleSize( ratios->GetYaxis()->GetTitleSize() * 4.0/3.0 );
ratios->GetXaxis()->SetLabelSize( ratios->GetYaxis()->GetLabelSize()  );
ratios->GetYaxis()->SetNdivisions(505);
ratios->Draw();
ratiosn->Draw("SAME");
ratios->Draw("p SAME");

//HoE_online = HoE * pt / min(127,pt) < 3(6)% in EE(EE)
//c1->SaveAs("/afs/cern.ch/user/m/mquittna/www/diphoton/spring16/singlePho/promptEE_chIso.png");
//c1->SaveAs("/afs/cern.ch/user/m/mquittna/www/diphoton/spring16/singlePho/promptEE_chIso.root");
c1->SaveAs("/afs/cern.ch/user/m/mquittna/www/diphoton/spring16/singlePho/sidebandEE_chIso.png");
c1->SaveAs("/afs/cern.ch/user/m/mquittna/www/diphoton/spring16/singlePho/sidebandEE_chIso.root");
}
